language: node_js
node_js:
  - "4.4.0"
install: true
before_install:
  - apt-get update
  - apt-get install -y wget
  - npm install
script:
  - npm test
notifications:
  slack: 'inist-dpi:53Jp5iUZeRidSGZn0TukMSKo#activity'